spring.application.name=plantenkennis-api
spring.jpa.open-in-view=false

# ===============================
# Database configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/novi_plantenkennis
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# Keycloak
# ===============================
client-id=plantenkennis_portal
client-secret=fNfnzB21YiPXrum5VH7pydNfY8ubZyRQ
audience=account
issuer-uri=http://localhost:9090/realms/Plantenkennis
spring.security.oauth2.resourceserver.jwt.issuer-uri=${issuer-uri}
spring.security.oauth2.resourceserver.jwt.audiences=${audience}
